# Generated by Django 3.0.8 on 2020-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200727_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
